{
 "title": "Weather",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "station", "label": "station", "query": { "query": "label_values(station)" } }
  ]
 },
 "panels": [
  { "title": "Weather Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 }, "options": { "content": "# Indoors" } },
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 3, "y": 1 }, "options": { "content": "# Outdoors" } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_tempinf{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_tempf{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_uv{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "in/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_hourlyrainin{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_winddir{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_humidityin{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_humidity{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_windspeedmph{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Gust Speeds",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_windgustmph{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Soil Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_temp1f{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 }, "options": { "content": "# Batteries" } },
  {
   "title": "Air Quality",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_pm25{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Station",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_battout{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Air Monitor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_batt_25{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Soil Probe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_batt1{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_solarradiation{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Growing Days Left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(1758859200 - time()) / 86400", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Absolute Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_baromabsin{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awp_baromrelin{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Historic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": " Total Rain",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "awp_hourlyrainin{station=\"$station\"} * $__interval_ms / 3600000",
     "legendFormat": "Inches"
    }
   ]
  },
  {
   "title": "Outdoor Humidity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "awp_humidity{station=\"$station\"}",
     "legendFormat": "Outdoor Humidity"
    }
   ]
  },
  {
   "title": "Outdoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "awp_tempf{station=\"$station\"}",
     "legendFormat": "Outdoor Temperature"
    }
   ]
  },
  {
   "title": " Rain Inches / Hour",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "In/hr" } },
   "targets": [
    {
     "expr": "awp_hourlyrainin{station=\"$station\"}",
     "legendFormat": "In/hr"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "awp_uv{station=\"$station\"}",
     "legendFormat": "UV Index"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "awp_pm25{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "awp_windspeedmph{station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "awp_winddir{station=\"$station\"} * (awp_winddir{station=\"$station\"} > bool 22.5)\n+\n359 * (awp_winddir{station=\"$station\"} <= bool 22.5)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}